# Base image with Nginx
FROM nginx:latest

# Copy the custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Create a directory for SSL certificates and copy them into the container
RUN mkdir -p /etc/nginx/certs
COPY ssl-certs/cert.pem /etc/nginx/certs/
COPY ssl-certs/privkey.pem /etc/nginx/certs/

# Expose ports for HTTP and HTTPS
EXPOSE 80
EXPOSE 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
