version: "3.8"

services:
  traccar:
    image: my_traccar:latest
    container_name: traccar
    hostname: traccar
    restart: unless-stopped
    ports:
      - "8082:80"
      - "5000-5150:5000-5150"
      - "5000-5150:5000-5150/udp"
    volumes:
      - ./traccar.xml:/opt/traccar/conf/traccar.xml:ro
