version: "3"

services:
  traccar:
    build:
      context: ./traccar
      dockerfile: Dockerfile
    container_name: traccar
    hostname: traccar
    restart: unless-stopped
    ports:
      - "8082:8082"
    volumes:
      - ./traccar.xml:/opt/traccar/conf/traccar.xml:ro

  nginx-proxy:
    build:
      context: ./nginx-proxy-manager
      dockerfile: Dockerfile.nginx
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/hbref.gq-0001/:/etc/letsencrypt
      - ./appdata:/data
      - ./nginx.conf:/etc/nginx/conf.d/my_proxy.conf:ro
